export default ACTIONS = {
  SET_IMC: '@calculator/SET_IMC',
  CLEAR_RESULT: '@calculator/CLEAR_RESULT',
  SET_ENABLED_CATEGORY: '@calculator/SET_ENABLED_CATEGORY',
  SET_PESO_IDEAL: '@calculator/SET_PESO_IDEAL',
  SET_RCQ: '@calculator/SET_RCQ',
  SET_ALTURA_ESTIMADA: '@calculator/SET_ALTURA_ESTIMADA',
  SET_ADEQUACAO_DE_PESO: '@calculator/SET_ADEQUACAO_DE_PESO',
  SET_MUDANCA_DO_PEDO: '@calculator/SET_MUDANCA_DO_PEDO',
};
